language: node_js
node_js:
  - 6
  - 8
  # - 10 Ignore nodeJs 10 until https://github.com/firebase/firebase-js-sdk/issues/883 is resolved.

install:
  - npm install

script:
  - npm run build

after_success:
  - npm run coverage